const symptomWithId = [
    { name: "Itching", id: "itching" },
    { name: "Skin Rash", id: "skin_rash" },
    { name: "Nodal Skin Eruptions", id: "nodal_skin_eruptions" },
    { name: "Continuous Sneezing", id: "continuous_sneezing" },
    { name: "Shivering", id: "shivering" },
    { name: "Chills", id: "chills" },
    { name: "Joint Pain", id: "joint_pain" },
    { name: "Stomach Pain", id: "stomach_pain" },
    { name: "Acidity", id: "acidity" },
    { name: "Ulcers on Tongue", id: "ulcers_on_tongue" },
    { name: "Muscle Wasting", id: "muscle_wasting" },
    { name: "Vomiting", id: "vomiting" },
    { name: "Burning Micturition", id: "burning_micturition" },
    { name: "Spotting Urination", id: "spotting_urination" },
    { name: "Fatigue", id: "fatigue" },
    { name: "Weight Gain", id: "weight_gain" },
    { name: "Anxiety", id: "anxiety" },
    { name: "Cold Hands and Feets", id: "cold_hands_and_feets" },
    { name: "Mood Swings", id: "mood_swings" },
    { name: "Weight Loss", id: "weight_loss" },
    { name: "Restlessness", id: "restlessness" },
    { name: "Lethargy", id: "lethargy" },
    { name: "Patches in Throat", id: "patches_in_throat" },
    { name: "Irregular Sugar Level", id: "irregular_sugar_level" },
    { name: "Cough", id: "cough" },
    { name: "High Fever", id: "high_fever" },
    { name: "Sunken Eyes", id: "sunken_eyes" },
    { name: "Breathlessness", id: "breathlessness" },
    { name: "Sweating", id: "sweating" },
    { name: "Dehydration", id: "dehydration" },
    { name: "Indigestion", id: "indigestion" },
    { name: "Headache", id: "headache" },
    { name: "Yellowish Skin", id: "yellowish_skin" },
    { name: "Dark Urine", id: "dark_urine" },
    { name: "Nausea", id: "nausea" },
    { name: "Loss of Appetite", id: "loss_of_appetite" },
    { name: "Pain Behind the Eyes", id: "pain_behind_the_eyes" },
    { name: "Back Pain", id: "back_pain" },
    { name: "Constipation", id: "constipation" },
    { name: "Abdominal Pain", id: "abdominal_pain" },
    { name: "Diarrhoea", id: "diarrhoea" },
    { name: "Mild Fever", id: "mild_fever" },
    { name: "Yellow Urine", id: "yellow_urine" },
    { name: "Yellowing of Eyes", id: "yellowing_of_eyes" },
    { name: "Acute Liver Failure", id: "acute_liver_failure" },
    { name: "Fluid Overload", id: "fluid_overload" },
    { name: "Swelling of Stomach", id: "swelling_of_stomach" },
    { name: "Swelled Lymph Nodes", id: "swelled_lymph_nodes" },
    { name: "Malaise", id: "malaise" },
    {
        name: "Blurred and Distorted Vision",
        id: "blurred_and_distorted_vision",
    },
    { name: "Phlegm", id: "phlegm" },
    { name: "Throat Irritation", id: "throat_irritation" },
    { name: "Redness of Eyes", id: "redness_of_eyes" },
    { name: "Sinus Pressure", id: "sinus_pressure" },
    { name: "Runny Nose", id: "runny_nose" },
    { name: "Congestion", id: "congestion" },
    { name: "Chest Pain", id: "chest_pain" },
    { name: "Weakness in Limbs", id: "weakness_in_limbs" },
    { name: "Fast Heart Rate", id: "fast_heart_rate" },
    { name: "Pain During Bowel Movements", id: "pain_during_bowel_movements" },
    { name: "Pain in Anal Region", id: "pain_in_anal_region" },
    { name: "Bloody Stool", id: "bloody_stool" },
    { name: "Irritation in Anus", id: "irritation_in_anus" },
    { name: "Neck Pain", id: "neck_pain" },
    { name: "Dizziness", id: "dizziness" },
    { name: "Cramps", id: "cramps" },
    { name: "Bruising", id: "bruising" },
    { name: "Obesity", id: "obesity" },
    { name: "Swollen Legs", id: "swollen_legs" },
    { name: "Swollen Blood Vessels", id: "swollen_blood_vessels" },
    { name: "Puffy Face and Eyes", id: "puffy_face_and_eyes" },
    { name: "Enlarged Thyroid", id: "enlarged_thyroid" },
    { name: "Brittle Nails", id: "brittle_nails" },
    { name: "Swollen Extremities", id: "swollen_extremities" },
    { name: "Excessive Hunger", id: "excessive_hunger" },
    { name: "Extra Marital Contacts", id: "extra_marital_contacts" },
    { name: "Drying and Tingling Lips", id: "drying_and_tingling_lips" },
    { name: "Slurred Speech", id: "slurred_speech" },
    { name: "Knee Pain", id: "knee_pain" },
    { name: "Hip Joint Pain", id: "hip_joint_pain" },
    { name: "Muscle Weakness", id: "muscle_weakness" },
    { name: "Stiff Neck", id: "stiff_neck" },
    { name: "Swelling Joints", id: "swelling_joints" },
    { name: "Movement Stiffness", id: "movement_stiffness" },
    { name: "Spinning Movements", id: "spinning_movements" },
    { name: "Loss of Balance", id: "loss_of_balance" },
    { name: "Unsteadiness", id: "unsteadiness" },
    { name: "Weakness of One Body Side", id: "weakness_of_one_body_side" },
    { name: "Loss of Smell", id: "loss_of_smell" },
    { name: "Bladder Discomfort", id: "bladder_discomfort" },
    { name: "Foul Smell of Urine", id: "foul_smell_of_urine" },
    { name: "Continuous Feel of Urine", id: "continuous_feel_of_urine" },
    { name: "Passage of Gases", id: "passage_of_gases" },
    { name: "Internal Itching", id: "internal_itching" },
    { name: "Toxic Look (Typhos)", id: "toxic_look_typhos" },
    { name: "Depression", id: "depression" },
    { name: "Irritability", id: "irritability" },
    { name: "Muscle Pain", id: "muscle_pain" },
    { name: "Altered Sensorium", id: "altered_sensorium" },
    { name: "Red Spots Over Body", id: "red_spots_over_body" },
    { name: "Belly Pain", id: "belly_pain" },
    { name: "Abnormal Menstruation", id: "abnormal_menstruation" },
    { name: "Dischromic Patches", id: "dischromic_patches" },
    { name: "Watering from Eyes", id: "watering_from_eyes" },
    { name: "Increased Appetite", id: "increased_appetite" },
    { name: "Polyuria", id: "polyuria" },
    { name: "Family History", id: "family_history" },
    { name: "Mucoid Sputum", id: "mucoid_sputum" },
    { name: "Rusty Sputum", id: "rusty_sputum" },
    { name: "Lack of Concentration", id: "lack_of_concentration" },
    { name: "Visual Disturbances", id: "visual_disturbances" },
    { name: "Receiving Blood Transfusion", id: "receiving_blood_transfusion" },
    {
        name: "Receiving Unsterile Injections",
        id: "receiving_unsterile_injections",
    },
    { name: "Coma", id: "coma" },
    { name: "Stomach Bleeding", id: "stomach_bleeding" },
    { name: "Distention of Abdomen", id: "distention_of_abdomen" },
    {
        name: "History of Alcohol Consumption",
        id: "history_of_alcohol_consumption",
    },
    { name: "Fluid Overload", id: "fluid_overload_2" },
    { name: "Blood in Sputum", id: "blood_in_sputum" },
    { name: "Prominent Veins on Calf", id: "prominent_veins_on_calf" },
    { name: "Palpitations", id: "palpitations" },
    { name: "Painful Walking", id: "painful_walking" },
    { name: "Pus Filled Pimples", id: "pus_filled_pimples" },
    { name: "Blackheads", id: "blackheads" },
    { name: "Scurring", id: "scurring" },
    { name: "Skin Peeling", id: "skin_peeling" },
    { name: "Silver Like Dusting", id: "silver_like_dusting" },
    { name: "Small Dents in Nails", id: "small_dents_in_nails" },
    { name: "Inflammatory Nails", id: "inflammatory_nails" },
    { name: "Blister", id: "blister" },
    { name: "Red Sore Around Nose", id: "red_sore_around_nose" },
    { name: "Yellow Crust Ooze", id: "yellow_crust_ooze" },
    { name: "Prognosis", id: "prognosis" },
];

export default symptomWithId;
